name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      EXECUTABLE_SUFF: ${{ github.gead_ref }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

    - name: Build for Linux
      env:
        GOOS: linux
        GOARCH: amd64
         
      run: |
        mkdir -p build/linux && \
        go build -v -o build/linux ./... && \
        mv ./build/linux/cmd ./build/linux/crypto-${{ env.EXECUTABLE_SUFF }}-linux.bin

    - name: Build for Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        mkdir -p build/windows && \
        go build -v -o build/windows ./... && \
        mv ./build/windows/cmd.exe ./build/windows/crypto-${{ env.EXECUTABLE_SUFF }}-windows.exe
        
    - name: Upload artifacts artifacts
      uses: actions/upload-artifact@v2
      with:
        name: distrinb
        path: |
          build/linux
          build/windows
